let result;
//take the var data and its
let data = [
	{
		"county": "Albany County",
		"total_pop": "308,195",
		"total_prison_pop": "1,756",
		"percent_of_total_pop_that_are_incarcerated": "0.57%",
		"black_prison_pop": "1,128",
		"percent_of_total_incarcerated_pop_that_are_black": "64.24%",
		"white_prison_pop": 388,
		"latino_prison_pop": 192,
		"male_prison_pop": "1,679",
		"female_prison_pop": 77
  },
	{
		"county": "Allegany County",
		"total_pop": "47,694",
		"total_prison_pop": 75,
		"percent_of_total_pop_that_are_incarcerated": "0.16%",
		"black_prison_pop": "",
		"percent_of_total_incarcerated_pop_that_are_black": "",
		"white_prison_pop": 70,
		"latino_prison_pop": "",
		"male_prison_pop": 66,
		"female_prison_pop": 9
  },
	{
		"county": "Broome County",
		"total_pop": "197,649",
		"total_prison_pop": 722,
		"percent_of_total_pop_that_are_incarcerated": "0.37%",
		"black_prison_pop": 301,
		"percent_of_total_incarcerated_pop_that_are_black": "41.69%",
		"white_prison_pop": 347,
		"latino_prison_pop": 57,
		"male_prison_pop": 670,
		"female_prison_pop": 52
  },
	{
		"county": "Cattaraugus County",
		"total_pop": "78,726",
		"total_prison_pop": 190,
		"percent_of_total_pop_that_are_incarcerated": "0.24%",
		"black_prison_pop": 38,
		"percent_of_total_incarcerated_pop_that_are_black": "20.00%",
		"white_prison_pop": 121,
		"latino_prison_pop": 8,
		"male_prison_pop": 176,
		"female_prison_pop": 14
  },
	{
		"county": "Cayuga County",
		"total_pop": "78,800",
		"total_prison_pop": 320,
		"percent_of_total_pop_that_are_incarcerated": "0.41%",
		"black_prison_pop": 94,
		"percent_of_total_incarcerated_pop_that_are_black": "29.38%",
		"white_prison_pop": 207,
		"latino_prison_pop": 16,
		"male_prison_pop": 300,
		"female_prison_pop": 20
  },
	{
		"county": "Chautauqua County",
		"total_pop": "131,892",
		"total_prison_pop": 254,
		"percent_of_total_pop_that_are_incarcerated": "0.19%",
		"black_prison_pop": 64,
		"percent_of_total_incarcerated_pop_that_are_black": "25.20%",
		"white_prison_pop": 142,
		"latino_prison_pop": 41,
		"male_prison_pop": 243,
		"female_prison_pop": 11
  },
	{
		"county": "Chemung County",
		"total_pop": "87,414",
		"total_prison_pop": 330,
		"percent_of_total_pop_that_are_incarcerated": "0.38%",
		"black_prison_pop": 135,
		"percent_of_total_incarcerated_pop_that_are_black": "40.91%",
		"white_prison_pop": 170,
		"latino_prison_pop": 21,
		"male_prison_pop": 312,
		"female_prison_pop": 18
  },
	{
		"county": "Chenango County",
		"total_pop": "49,340",
		"total_prison_pop": 141,
		"percent_of_total_pop_that_are_incarcerated": "0.29%",
		"black_prison_pop": 20,
		"percent_of_total_incarcerated_pop_that_are_black": "14.18%",
		"white_prison_pop": 108,
		"latino_prison_pop": 11,
		"male_prison_pop": 126,
		"female_prison_pop": 15
  },
	{
		"county": "Clinton County",
		"total_pop": "81,549",
		"total_prison_pop": 412,
		"percent_of_total_pop_that_are_incarcerated": "0.51%",
		"black_prison_pop": 70,
		"percent_of_total_incarcerated_pop_that_are_black": "16.99%",
		"white_prison_pop": 302,
		"latino_prison_pop": 20,
		"male_prison_pop": 356,
		"female_prison_pop": 56
  },
	{
		"county": "Columbia County",
		"total_pop": "62,018",
		"total_prison_pop": 144,
		"percent_of_total_pop_that_are_incarcerated": "0.23%",
		"black_prison_pop": 39,
		"percent_of_total_incarcerated_pop_that_are_black": "27.08%",
		"white_prison_pop": 89,
		"latino_prison_pop": 9,
		"male_prison_pop": 132,
		"female_prison_pop": 12
  },
	{
		"county": "Cortland County",
		"total_pop": "48,742",
		"total_prison_pop": 155,
		"percent_of_total_pop_that_are_incarcerated": "0.32%",
		"black_prison_pop": 25,
		"percent_of_total_incarcerated_pop_that_are_black": "16.13%",
		"white_prison_pop": 114,
		"latino_prison_pop": 14,
		"male_prison_pop": 143,
		"female_prison_pop": 12
  },
	{
		"county": "Delaware County",
		"total_pop": "46,560",
		"total_prison_pop": 128,
		"percent_of_total_pop_that_are_incarcerated": "0.27%",
		"black_prison_pop": 8,
		"percent_of_total_incarcerated_pop_that_are_black": "6.25%",
		"white_prison_pop": 112,
		"latino_prison_pop": 7,
		"male_prison_pop": 111,
		"female_prison_pop": 17
  },
	{
		"county": "Dutchess County",
		"total_pop": "296,058",
		"total_prison_pop": 692,
		"percent_of_total_pop_that_are_incarcerated": "0.23%",
		"black_prison_pop": 314,
		"percent_of_total_incarcerated_pop_that_are_black": "45.38%",
		"white_prison_pop": 252,
		"latino_prison_pop": 101,
		"male_prison_pop": 647,
		"female_prison_pop": 45
  },
	{
		"county": "Erie County",
		"total_pop": "924,449",
		"total_prison_pop": "2,567",
		"percent_of_total_pop_that_are_incarcerated": "0.28%",
		"black_prison_pop": "1,660",
		"percent_of_total_incarcerated_pop_that_are_black": "64.67%",
		"white_prison_pop": 591,
		"latino_prison_pop": 251,
		"male_prison_pop": "2,477",
		"female_prison_pop": 90
  },
	{
		"county": "Essex County",
		"total_pop": "38,380",
		"total_prison_pop": 97,
		"percent_of_total_pop_that_are_incarcerated": "0.25%",
		"black_prison_pop": "",
		"percent_of_total_incarcerated_pop_that_are_black": "",
		"white_prison_pop": 87,
		"latino_prison_pop": "",
		"male_prison_pop": 90,
		"female_prison_pop": 7
  },
	{
		"county": "Franklin County",
		"total_pop": "51,158",
		"total_prison_pop": 167,
		"percent_of_total_pop_that_are_incarcerated": "0.33%",
		"black_prison_pop": 10,
		"percent_of_total_incarcerated_pop_that_are_black": "5.99%",
		"white_prison_pop": 135,
		"latino_prison_pop": 4,
		"male_prison_pop": 150,
		"female_prison_pop": 17
  },
	{
		"county": "Fulton County",
		"total_pop": "53,975",
		"total_prison_pop": 159,
		"percent_of_total_pop_that_are_incarcerated": "0.29%",
		"black_prison_pop": 35,
		"percent_of_total_incarcerated_pop_that_are_black": "22.01%",
		"white_prison_pop": 110,
		"latino_prison_pop": 9,
		"male_prison_pop": 148,
		"female_prison_pop": 11
  },
	{
		"county": "Genesee County",
		"total_pop": "58,807",
		"total_prison_pop": 277,
		"percent_of_total_pop_that_are_incarcerated": "0.47%",
		"black_prison_pop": 69,
		"percent_of_total_incarcerated_pop_that_are_black": "24.91%",
		"white_prison_pop": 184,
		"latino_prison_pop": 18,
		"male_prison_pop": 253,
		"female_prison_pop": 24
  },
	{
		"county": "Greene County",
		"total_pop": "47,984",
		"total_prison_pop": 135,
		"percent_of_total_pop_that_are_incarcerated": "0.28%",
		"black_prison_pop": 34,
		"percent_of_total_incarcerated_pop_that_are_black": "25.19%",
		"white_prison_pop": 77,
		"latino_prison_pop": 21,
		"male_prison_pop": 120,
		"female_prison_pop": 15
  },
	{
		"county": "Hamilton County",
		"total_pop": "4,703",
		"total_prison_pop": 11,
		"percent_of_total_pop_that_are_incarcerated": "0.23%",
		"black_prison_pop": "",
		"percent_of_total_incarcerated_pop_that_are_black": "",
		"white_prison_pop": 8,
		"latino_prison_pop": 0,
		"male_prison_pop": 11,
		"female_prison_pop": 0
  },
	{
		"county": "Herkimer County",
		"total_pop": "63,407",
		"total_prison_pop": 200,
		"percent_of_total_pop_that_are_incarcerated": "0.32%",
		"black_prison_pop": 29,
		"percent_of_total_incarcerated_pop_that_are_black": "14.50%",
		"white_prison_pop": 163,
		"latino_prison_pop": 8,
		"male_prison_pop": 187,
		"female_prison_pop": 13
  },
	{
		"county": "Jefferson County",
		"total_pop": "119,044",
		"total_prison_pop": 270,
		"percent_of_total_pop_that_are_incarcerated": "0.23%",
		"black_prison_pop": 73,
		"percent_of_total_incarcerated_pop_that_are_black": "27.04%",
		"white_prison_pop": 172,
		"latino_prison_pop": 20,
		"male_prison_pop": 239,
		"female_prison_pop": 31
  },
	{
		"county": "Lewis County",
		"total_pop": "27,096",
		"total_prison_pop": 61,
		"percent_of_total_pop_that_are_incarcerated": "0.23%",
		"black_prison_pop": 7,
		"percent_of_total_incarcerated_pop_that_are_black": "11.48%",
		"white_prison_pop": 51,
		"latino_prison_pop": "",
		"male_prison_pop": 55,
		"female_prison_pop": 6
  },
	{
		"county": "Livingston County",
		"total_pop": "64,666",
		"total_prison_pop": 177,
		"percent_of_total_pop_that_are_incarcerated": "0.27%",
		"black_prison_pop": 19,
		"percent_of_total_incarcerated_pop_that_are_black": "10.73%",
		"white_prison_pop": 146,
		"latino_prison_pop": 11,
		"male_prison_pop": 160,
		"female_prison_pop": 17
  },
	{
		"county": "Madison County",
		"total_pop": "72,241",
		"total_prison_pop": 119,
		"percent_of_total_pop_that_are_incarcerated": "0.16%",
		"black_prison_pop": 12,
		"percent_of_total_incarcerated_pop_that_are_black": "10.08%",
		"white_prison_pop": 104,
		"latino_prison_pop": "",
		"male_prison_pop": 107,
		"female_prison_pop": 12
  },
	{
		"county": "Monroe County",
		"total_pop": "749,803",
		"total_prison_pop": "3,189",
		"percent_of_total_pop_that_are_incarcerated": "0.43%",
		"black_prison_pop": "2,113",
		"percent_of_total_incarcerated_pop_that_are_black": "66.26%",
		"white_prison_pop": 593,
		"latino_prison_pop": 434,
		"male_prison_pop": "3,043",
		"female_prison_pop": 146
  },
	{
		"county": "Montgomery County",
		"total_pop": "49,667",
		"total_prison_pop": 161,
		"percent_of_total_pop_that_are_incarcerated": "0.32%",
		"black_prison_pop": 17,
		"percent_of_total_incarcerated_pop_that_are_black": "10.56%",
		"white_prison_pop": 78,
		"latino_prison_pop": 63,
		"male_prison_pop": 153,
		"female_prison_pop": 8
  },
	{
		"county": "Nassau County",
		"total_pop": "1,360,703",
		"total_prison_pop": "1,648",
		"percent_of_total_pop_that_are_incarcerated": "0.12%",
		"black_prison_pop": 906,
		"percent_of_total_incarcerated_pop_that_are_black": "54.98%",
		"white_prison_pop": 348,
		"latino_prison_pop": 346,
		"male_prison_pop": "1,583",
		"female_prison_pop": 65
  },
	{
		"county": "New York County",
		"total_pop": "8,521,135",
		"total_prison_pop": "22,301",
		"percent_of_total_pop_that_are_incarcerated": "0.26%",
		"black_prison_pop": "12,395",
		"percent_of_total_incarcerated_pop_that_are_black": "55.58%",
		"white_prison_pop": "1,647",
		"latino_prison_pop": "7,444",
		"male_prison_pop": "21,623",
		"female_prison_pop": 678
  },
	{
		"county": "Niagara County",
		"total_pop": "213,475",
		"total_prison_pop": 649,
		"percent_of_total_pop_that_are_incarcerated": "0.30%",
		"black_prison_pop": 297,
		"percent_of_total_incarcerated_pop_that_are_black": "45.76%",
		"white_prison_pop": 280,
		"latino_prison_pop": 37,
		"male_prison_pop": 614,
		"female_prison_pop": 35
  },
	{
		"county": "Oneida County",
		"total_pop": "233,229",
		"total_prison_pop": "1,015",
		"percent_of_total_pop_that_are_incarcerated": "0.44%",
		"black_prison_pop": 424,
		"percent_of_total_incarcerated_pop_that_are_black": "41.77%",
		"white_prison_pop": 455,
		"latino_prison_pop": 117,
		"male_prison_pop": 958,
		"female_prison_pop": 57
  },
	{
		"county": "Onondaga County",
		"total_pop": "468,827",
		"total_prison_pop": "1,885",
		"percent_of_total_pop_that_are_incarcerated": "0.40%",
		"black_prison_pop": "1,053",
		"percent_of_total_incarcerated_pop_that_are_black": "55.86%",
		"white_prison_pop": 529,
		"latino_prison_pop": 233,
		"male_prison_pop": "1,804",
		"female_prison_pop": 81
  },
	{
		"county": "Ontario County",
		"total_pop": "109,420",
		"total_prison_pop": 534,
		"percent_of_total_pop_that_are_incarcerated": "0.49%",
		"black_prison_pop": 147,
		"percent_of_total_incarcerated_pop_that_are_black": "27.53%",
		"white_prison_pop": 304,
		"latino_prison_pop": 78,
		"male_prison_pop": 469,
		"female_prison_pop": 65
  },
	{
		"county": "Orange County",
		"total_pop": "376,034",
		"total_prison_pop": "1,006",
		"percent_of_total_pop_that_are_incarcerated": "0.27%",
		"black_prison_pop": 452,
		"percent_of_total_incarcerated_pop_that_are_black": "44.93%",
		"white_prison_pop": 270,
		"latino_prison_pop": 259,
		"male_prison_pop": 963,
		"female_prison_pop": 43
  },
	{
		"county": "Orleans County",
		"total_pop": "41,890",
		"total_prison_pop": 147,
		"percent_of_total_pop_that_are_incarcerated": "0.35%",
		"black_prison_pop": 32,
		"percent_of_total_incarcerated_pop_that_are_black": "21.77%",
		"white_prison_pop": 99,
		"latino_prison_pop": 14,
		"male_prison_pop": 132,
		"female_prison_pop": 15
  },
	{
		"county": "Oswego County",
		"total_pop": "120,657",
		"total_prison_pop": 368,
		"percent_of_total_pop_that_are_incarcerated": "0.30%",
		"black_prison_pop": 30,
		"percent_of_total_incarcerated_pop_that_are_black": "8.15%",
		"white_prison_pop": 307,
		"latino_prison_pop": 17,
		"male_prison_pop": 345,
		"female_prison_pop": 23
  },
	{
		"county": "Otsego County",
		"total_pop": "60,994",
		"total_prison_pop": 119,
		"percent_of_total_pop_that_are_incarcerated": "0.20%",
		"black_prison_pop": 17,
		"percent_of_total_incarcerated_pop_that_are_black": "14.29%",
		"white_prison_pop": 87,
		"latino_prison_pop": 14,
		"male_prison_pop": 108,
		"female_prison_pop": 11
  },
	{
		"county": "Putnam County",
		"total_pop": "99,667",
		"total_prison_pop": 91,
		"percent_of_total_pop_that_are_incarcerated": "0.09%",
		"black_prison_pop": 11,
		"percent_of_total_incarcerated_pop_that_are_black": "12.09%",
		"white_prison_pop": 55,
		"latino_prison_pop": 21,
		"male_prison_pop": 84,
		"female_prison_pop": 7
  },
	{
		"county": "Rensselaer County",
		"total_pop": "159,938",
		"total_prison_pop": 433,
		"percent_of_total_pop_that_are_incarcerated": "0.27%",
		"black_prison_pop": 183,
		"percent_of_total_incarcerated_pop_that_are_black": "42.26%",
		"white_prison_pop": 184,
		"latino_prison_pop": 54,
		"male_prison_pop": 414,
		"female_prison_pop": 19
  },
	{
		"county": "Rockland County",
		"total_pop": "323,072",
		"total_prison_pop": 375,
		"percent_of_total_pop_that_are_incarcerated": "0.12%",
		"black_prison_pop": 173,
		"percent_of_total_incarcerated_pop_that_are_black": "46.13%",
		"white_prison_pop": 75,
		"latino_prison_pop": 109,
		"male_prison_pop": 361,
		"female_prison_pop": 14
  },
	{
		"county": "Saratoga County",
		"total_pop": "224,872",
		"total_prison_pop": 303,
		"percent_of_total_pop_that_are_incarcerated": "0.13%",
		"black_prison_pop": 44,
		"percent_of_total_incarcerated_pop_that_are_black": "14.52%",
		"white_prison_pop": 228,
		"latino_prison_pop": 23,
		"male_prison_pop": 265,
		"female_prison_pop": 38
  },
	{
		"county": "Schenectady County",
		"total_pop": "155,340",
		"total_prison_pop": 765,
		"percent_of_total_pop_that_are_incarcerated": "0.49%",
		"black_prison_pop": 430,
		"percent_of_total_incarcerated_pop_that_are_black": "56.21%",
		"white_prison_pop": 205,
		"latino_prison_pop": 103,
		"male_prison_pop": 710,
		"female_prison_pop": 55
  },
	{
		"county": "Schoharie County",
		"total_pop": "31,795",
		"total_prison_pop": 41,
		"percent_of_total_pop_that_are_incarcerated": "0.13%",
		"black_prison_pop": "",
		"percent_of_total_incarcerated_pop_that_are_black": "",
		"white_prison_pop": 38,
		"latino_prison_pop": "",
		"male_prison_pop": 37,
		"female_prison_pop": 4
  },
	{
		"county": "Schuyler County",
		"total_pop": "18,170",
		"total_prison_pop": 44,
		"percent_of_total_pop_that_are_incarcerated": "0.24%",
		"black_prison_pop": "",
		"percent_of_total_incarcerated_pop_that_are_black": "",
		"white_prison_pop": 39,
		"latino_prison_pop": "",
		"male_prison_pop": 38,
		"female_prison_pop": 6
  },
	{
		"county": "Seneca County",
		"total_pop": "34,890",
		"total_prison_pop": 73,
		"percent_of_total_pop_that_are_incarcerated": "0.21%",
		"black_prison_pop": 13,
		"percent_of_total_incarcerated_pop_that_are_black": "17.81%",
		"white_prison_pop": 53,
		"latino_prison_pop": 6,
		"male_prison_pop": 65,
		"female_prison_pop": 8
  },
	{
		"county": "St. Lawrence County",
		"total_pop": "111,601",
		"total_prison_pop": 306,
		"percent_of_total_pop_that_are_incarcerated": "0.27%",
		"black_prison_pop": 25,
		"percent_of_total_incarcerated_pop_that_are_black": "8.17%",
		"white_prison_pop": 258,
		"latino_prison_pop": 8,
		"male_prison_pop": 288,
		"female_prison_pop": 18
  },
	{
		"county": "Steuben County",
		"total_pop": "98,208",
		"total_prison_pop": 285,
		"percent_of_total_pop_that_are_incarcerated": "0.29%",
		"black_prison_pop": 47,
		"percent_of_total_incarcerated_pop_that_are_black": "16.49%",
		"white_prison_pop": 223,
		"latino_prison_pop": 8,
		"male_prison_pop": 260,
		"female_prison_pop": 25
  },
	{
		"county": "Suffolk County",
		"total_pop": "1,500,638",
		"total_prison_pop": "2,117",
		"percent_of_total_pop_that_are_incarcerated": "0.14%",
		"black_prison_pop": 869,
		"percent_of_total_incarcerated_pop_that_are_black": "41.05%",
		"white_prison_pop": 705,
		"latino_prison_pop": 472,
		"male_prison_pop": "2,034",
		"female_prison_pop": 83
  },
	{
		"county": "Sullivan County",
		"total_pop": "75,852",
		"total_prison_pop": 388,
		"percent_of_total_pop_that_are_incarcerated": "0.51%",
		"black_prison_pop": 125,
		"percent_of_total_incarcerated_pop_that_are_black": "32.22%",
		"white_prison_pop": 173,
		"latino_prison_pop": 74,
		"male_prison_pop": 364,
		"female_prison_pop": 24
  },
	{
		"county": "Tioga County",
		"total_pop": "49,820",
		"total_prison_pop": 78,
		"percent_of_total_pop_that_are_incarcerated": "0.16%",
		"black_prison_pop": 6,
		"percent_of_total_incarcerated_pop_that_are_black": "7.69%",
		"white_prison_pop": 65,
		"latino_prison_pop": 6,
		"male_prison_pop": 72,
		"female_prison_pop": 6
  },
	{
		"county": "Tompkins County",
		"total_pop": "104,286",
		"total_prison_pop": 171,
		"percent_of_total_pop_that_are_incarcerated": "0.16%",
		"black_prison_pop": 59,
		"percent_of_total_incarcerated_pop_that_are_black": "34.50%",
		"white_prison_pop": 92,
		"latino_prison_pop": 10,
		"male_prison_pop": 159,
		"female_prison_pop": 12
  },
	{
		"county": "Ulster County",
		"total_pop": "180,763",
		"total_prison_pop": 642,
		"percent_of_total_pop_that_are_incarcerated": "0.36%",
		"black_prison_pop": 270,
		"percent_of_total_incarcerated_pop_that_are_black": "42.06%",
		"white_prison_pop": 268,
		"latino_prison_pop": 83,
		"male_prison_pop": 614,
		"female_prison_pop": 28
  },
	{
		"county": "Warren County",
		"total_pop": "64,901",
		"total_prison_pop": 355,
		"percent_of_total_pop_that_are_incarcerated": "0.55%",
		"black_prison_pop": 62,
		"percent_of_total_incarcerated_pop_that_are_black": "17.46%",
		"white_prison_pop": 259,
		"latino_prison_pop": 21,
		"male_prison_pop": 298,
		"female_prison_pop": 57
  },
	{
		"county": "Washington County",
		"total_pop": "62,478",
		"total_prison_pop": 236,
		"percent_of_total_pop_that_are_incarcerated": "0.38%",
		"black_prison_pop": 30,
		"percent_of_total_incarcerated_pop_that_are_black": "12.71%",
		"white_prison_pop": 175,
		"latino_prison_pop": 17,
		"male_prison_pop": 216,
		"female_prison_pop": 20
  },
	{
		"county": "Wayne County",
		"total_pop": "91,856",
		"total_prison_pop": 210,
		"percent_of_total_pop_that_are_incarcerated": "0.23%",
		"black_prison_pop": 76,
		"percent_of_total_incarcerated_pop_that_are_black": "36.19%",
		"white_prison_pop": 108,
		"latino_prison_pop": 19,
		"male_prison_pop": 195,
		"female_prison_pop": 15
  },
	{
		"county": "Westchester County",
		"total_pop": "972,742",
		"total_prison_pop": "1,301",
		"percent_of_total_pop_that_are_incarcerated": "0.13%",
		"black_prison_pop": 719,
		"percent_of_total_incarcerated_pop_that_are_black": "55.27%",
		"white_prison_pop": 173,
		"latino_prison_pop": 372,
		"male_prison_pop": "1,264",
		"female_prison_pop": 37
  },
	{
		"county": "Wyoming County",
		"total_pop": "41,160",
		"total_prison_pop": 138,
		"percent_of_total_pop_that_are_incarcerated": "0.34%",
		"black_prison_pop": 17,
		"percent_of_total_incarcerated_pop_that_are_black": "12.32%",
		"white_prison_pop": 109,
		"latino_prison_pop": 9,
		"male_prison_pop": 124,
		"female_prison_pop": 14
  },
	{
		"county": "Yates County",
		"total_pop": "25,150",
		"total_prison_pop": 50,
		"percent_of_total_pop_that_are_incarcerated": "0.20%",
		"black_prison_pop": "",
		"percent_of_total_incarcerated_pop_that_are_black": "0.00%",
		"white_prison_pop": 43,
		"latino_prison_pop": 4,
		"male_prison_pop": 44,
		"female_prison_pop": 6
  }
]