let result;
//take the var data and its
let data = [{
		"county": "Albany County",
		"total_pop": "308,195",
		"total_prison_population": "1,756",
		"female_prison_pop": 77,
		"male_prison_pop": "1,679",
		"asian_prison_pop": 6,
		"black_prison_pop": "1,128",
		"latin_prison_pop": 192,
		"native_prison_pop": 10,
		"other_prison_pop": 32,
		"white_prison_pop": 388
	},
	{
		"county": "Allegany County",
		"total_pop": "47,694",
		"total_prison_population": 75,
		"female_prison_pop": 9,
		"male_prison_pop": 66,
		"asian_prison_pop": 0,
		"black_prison_pop": "Not Available",
		"latin_prison_pop": "Not Available",
		"native_prison_pop": "Not Available",
		"other_prison_pop": 5,
		"white_prison_pop": 70
	},
	{
		"county": "Broome County",
		"total_pop": "197,649",
		"total_prison_population": 722,
		"female_prison_pop": 52,
		"male_prison_pop": 670,
		"asian_prison_pop": 6,
		"black_prison_pop": 301,
		"latin_prison_pop": 57,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 11,
		"white_prison_pop": 347
	},
	{
		"county": "Cattaraugus County",
		"total_pop": "78,726",
		"total_prison_population": 190,
		"female_prison_pop": 14,
		"male_prison_pop": 176,
		"asian_prison_pop": 0,
		"black_prison_pop": 38,
		"latin_prison_pop": 8,
		"native_prison_pop": 22,
		"other_prison_pop": 1,
		"white_prison_pop": 121
	},
	{
		"county": "Cayuga County",
		"total_pop": "78,800",
		"total_prison_population": 320,
		"female_prison_pop": 20,
		"male_prison_pop": 300,
		"asian_prison_pop": 0,
		"black_prison_pop": 94,
		"latin_prison_pop": 16,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 3,
		"white_prison_pop": 207
	},
	{
		"county": "Chautauqua County",
		"total_pop": "131,892",
		"total_prison_population": 254,
		"female_prison_pop": 11,
		"male_prison_pop": 243,
		"asian_prison_pop": 0,
		"black_prison_pop": 64,
		"latin_prison_pop": 41,
		"native_prison_pop": 6,
		"other_prison_pop": 1,
		"white_prison_pop": 142
	},
	{
		"county": "Chemung County",
		"total_pop": "87,414",
		"total_prison_population": 330,
		"female_prison_pop": 18,
		"male_prison_pop": 312,
		"asian_prison_pop": 0,
		"black_prison_pop": 135,
		"latin_prison_pop": 21,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 4,
		"white_prison_pop": 170
	},
	{
		"county": "Chenango County",
		"total_pop": "49,340",
		"total_prison_population": 141,
		"female_prison_pop": 15,
		"male_prison_pop": 126,
		"asian_prison_pop": 0,
		"black_prison_pop": 20,
		"latin_prison_pop": 11,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 2,
		"white_prison_pop": 108
	},
	{
		"county": "Clinton County",
		"total_pop": "81,549",
		"total_prison_population": 412,
		"female_prison_pop": 56,
		"male_prison_pop": 356,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 70,
		"latin_prison_pop": 20,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 20,
		"white_prison_pop": 302
	},
	{
		"county": "Columbia County",
		"total_pop": "62,018",
		"total_prison_population": 144,
		"female_prison_pop": 12,
		"male_prison_pop": 132,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 39,
		"latin_prison_pop": 9,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 7,
		"white_prison_pop": 89
	},
	{
		"county": "Cortland County",
		"total_pop": "48,742",
		"total_prison_population": 155,
		"female_prison_pop": 12,
		"male_prison_pop": 143,
		"asian_prison_pop": 0,
		"black_prison_pop": 25,
		"latin_prison_pop": 14,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 2,
		"white_prison_pop": 114
	},
	{
		"county": "Delaware County",
		"total_pop": "46,560",
		"total_prison_population": 128,
		"female_prison_pop": 17,
		"male_prison_pop": 111,
		"asian_prison_pop": 0,
		"black_prison_pop": 8,
		"latin_prison_pop": 7,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 1,
		"white_prison_pop": 112
	},
	{
		"county": "Dutchess County",
		"total_pop": "296,058",
		"total_prison_population": 692,
		"female_prison_pop": 45,
		"male_prison_pop": 647,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 314,
		"latin_prison_pop": 101,
		"native_prison_pop": 6,
		"other_prison_pop": 19,
		"white_prison_pop": 252
	},
	{
		"county": "Erie County",
		"total_pop": "924,449",
		"total_prison_population": "2,567",
		"female_prison_pop": 90,
		"male_prison_pop": "2,477",
		"asian_prison_pop": 4,
		"black_prison_pop": "1,660",
		"latin_prison_pop": 251,
		"native_prison_pop": 33,
		"other_prison_pop": 28,
		"white_prison_pop": 591
	},
	{
		"county": "Essex County",
		"total_pop": "38,380",
		"total_prison_population": 97,
		"female_prison_pop": 7,
		"male_prison_pop": 90,
		"asian_prison_pop": 0,
		"black_prison_pop": "Not Available",
		"latin_prison_pop": "Not Available",
		"native_prison_pop": 0,
		"other_prison_pop": 10,
		"white_prison_pop": 87
	},
	{
		"county": "Franklin County",
		"total_pop": "51,158",
		"total_prison_population": 167,
		"female_prison_pop": 17,
		"male_prison_pop": 150,
		"asian_prison_pop": 0,
		"black_prison_pop": 10,
		"latin_prison_pop": 4,
		"native_prison_pop": 12,
		"other_prison_pop": 6,
		"white_prison_pop": 135
	},
	{
		"county": "Fulton County",
		"total_pop": "53,975",
		"total_prison_population": 159,
		"female_prison_pop": 11,
		"male_prison_pop": 148,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 35,
		"latin_prison_pop": 9,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 5,
		"white_prison_pop": 110
	},
	{
		"county": "Genesee County",
		"total_pop": "58,807",
		"total_prison_population": 277,
		"female_prison_pop": 24,
		"male_prison_pop": 253,
		"asian_prison_pop": 0,
		"black_prison_pop": 69,
		"latin_prison_pop": 18,
		"native_prison_pop": 6,
		"other_prison_pop": 0,
		"white_prison_pop": 184
	},
	{
		"county": "Greene County",
		"total_pop": "47,984",
		"total_prison_population": 135,
		"female_prison_pop": 15,
		"male_prison_pop": 120,
		"asian_prison_pop": 0,
		"black_prison_pop": 34,
		"latin_prison_pop": 21,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 3,
		"white_prison_pop": 77
	},
	{
		"county": "Hamilton County",
		"total_pop": "4,703",
		"total_prison_population": 11,
		"female_prison_pop": 0,
		"male_prison_pop": 11,
		"asian_prison_pop": 0,
		"black_prison_pop": "Not Available",
		"latin_prison_pop": 0,
		"native_prison_pop": 0,
		"other_prison_pop": 3,
		"white_prison_pop": 8
	},
	{
		"county": "Herkimer County",
		"total_pop": "63,407",
		"total_prison_population": 200,
		"female_prison_pop": 13,
		"male_prison_pop": 187,
		"asian_prison_pop": 0,
		"black_prison_pop": 29,
		"latin_prison_pop": 8,
		"native_prison_pop": 0,
		"other_prison_pop": 0,
		"white_prison_pop": 163
	},
	{
		"county": "Jefferson County",
		"total_pop": "119,044",
		"total_prison_population": 270,
		"female_prison_pop": 31,
		"male_prison_pop": 239,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 73,
		"latin_prison_pop": 20,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 5,
		"white_prison_pop": 172
	},
	{
		"county": "Lewis County",
		"total_pop": "27,096",
		"total_prison_population": 61,
		"female_prison_pop": 6,
		"male_prison_pop": 55,
		"asian_prison_pop": 0,
		"black_prison_pop": 7,
		"latin_prison_pop": "Not Available",
		"native_prison_pop": 0,
		"other_prison_pop": 3,
		"white_prison_pop": 51
	},
	{
		"county": "Livingston County",
		"total_pop": "64,666",
		"total_prison_population": 177,
		"female_prison_pop": 17,
		"male_prison_pop": 160,
		"asian_prison_pop": 0,
		"black_prison_pop": 19,
		"latin_prison_pop": 11,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 1,
		"white_prison_pop": 146
	},
	{
		"county": "Madison County",
		"total_pop": "72,241",
		"total_prison_population": 119,
		"female_prison_pop": 12,
		"male_prison_pop": 107,
		"asian_prison_pop": 0,
		"black_prison_pop": 12,
		"latin_prison_pop": "Not Available",
		"native_prison_pop": 0,
		"other_prison_pop": 3,
		"white_prison_pop": 104
	},
	{
		"county": "Monroe County",
		"total_pop": "749,803",
		"total_prison_population": "3,189",
		"female_prison_pop": 146,
		"male_prison_pop": "3,043",
		"asian_prison_pop": 8,
		"black_prison_pop": "2,113",
		"latin_prison_pop": 434,
		"native_prison_pop": 15,
		"other_prison_pop": 26,
		"white_prison_pop": 593
	},
	{
		"county": "Montgomery County",
		"total_pop": "49,667",
		"total_prison_population": 161,
		"female_prison_pop": 8,
		"male_prison_pop": 153,
		"asian_prison_pop": 0,
		"black_prison_pop": 17,
		"latin_prison_pop": 63,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 3,
		"white_prison_pop": 78
	},
	{
		"county": "Nassau County",
		"total_pop": "1,360,703",
		"total_prison_population": "1,648",
		"female_prison_pop": 65,
		"male_prison_pop": "1,583",
		"asian_prison_pop": 7,
		"black_prison_pop": 906,
		"latin_prison_pop": 346,
		"native_prison_pop": 8,
		"other_prison_pop": 33,
		"white_prison_pop": 348
	},
	{
		"county": "New York County",
		"total_pop": "8,521,135",
		"total_prison_population": "22,301",
		"female_prison_pop": 678,
		"male_prison_pop": "21,623",
		"asian_prison_pop": 169,
		"black_prison_pop": "12,395",
		"latin_prison_pop": "7,444",
		"native_prison_pop": 90,
		"other_prison_pop": 556,
		"white_prison_pop": "1,647"
	},
	{
		"county": "Niagara County",
		"total_pop": "213,475",
		"total_prison_population": 649,
		"female_prison_pop": 35,
		"male_prison_pop": 614,
		"asian_prison_pop": 0,
		"black_prison_pop": 297,
		"latin_prison_pop": 37,
		"native_prison_pop": 30,
		"other_prison_pop": 5,
		"white_prison_pop": 280
	},
	{
		"county": "Oneida County",
		"total_pop": "233,229",
		"total_prison_population": "1,015",
		"female_prison_pop": 57,
		"male_prison_pop": 958,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 424,
		"latin_prison_pop": 117,
		"native_prison_pop": 10,
		"other_prison_pop": 9,
		"white_prison_pop": 455
	},
	{
		"county": "Onondaga County",
		"total_pop": "468,827",
		"total_prison_population": "1,885",
		"female_prison_pop": 81,
		"male_prison_pop": "1,804",
		"asian_prison_pop": 7,
		"black_prison_pop": "1,053",
		"latin_prison_pop": 233,
		"native_prison_pop": 44,
		"other_prison_pop": 19,
		"white_prison_pop": 529
	},
	{
		"county": "Ontario County",
		"total_pop": "109,420",
		"total_prison_population": 534,
		"female_prison_pop": 65,
		"male_prison_pop": 469,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 147,
		"latin_prison_pop": 78,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 5,
		"white_prison_pop": 304
	},
	{
		"county": "Orange County",
		"total_pop": "376,034",
		"total_prison_population": "1,006",
		"female_prison_pop": 43,
		"male_prison_pop": 963,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 452,
		"latin_prison_pop": 259,
		"native_prison_pop": 8,
		"other_prison_pop": 17,
		"white_prison_pop": 270
	},
	{
		"county": "Orleans County",
		"total_pop": "41,890",
		"total_prison_population": 147,
		"female_prison_pop": 15,
		"male_prison_pop": 132,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 32,
		"latin_prison_pop": 14,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 2,
		"white_prison_pop": 99
	},
	{
		"county": "Oswego County",
		"total_pop": "120,657",
		"total_prison_population": 368,
		"female_prison_pop": 23,
		"male_prison_pop": 345,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 30,
		"latin_prison_pop": 17,
		"native_prison_pop": 9,
		"other_prison_pop": 5,
		"white_prison_pop": 307
	},
	{
		"county": "Otsego County",
		"total_pop": "60,994",
		"total_prison_population": 119,
		"female_prison_pop": 11,
		"male_prison_pop": 108,
		"asian_prison_pop": 0,
		"black_prison_pop": 17,
		"latin_prison_pop": 14,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 1,
		"white_prison_pop": 87
	},
	{
		"county": "Putnam County",
		"total_pop": "99,667",
		"total_prison_population": 91,
		"female_prison_pop": 7,
		"male_prison_pop": 84,
		"asian_prison_pop": 0,
		"black_prison_pop": 11,
		"latin_prison_pop": 21,
		"native_prison_pop": 0,
		"other_prison_pop": 4,
		"white_prison_pop": 55
	},
	{
		"county": "Rensselaer County",
		"total_pop": "159,938",
		"total_prison_population": 433,
		"female_prison_pop": 19,
		"male_prison_pop": 414,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 183,
		"latin_prison_pop": 54,
		"native_prison_pop": 4,
		"other_prison_pop": 8,
		"white_prison_pop": 184
	},
	{
		"county": "Rockland County",
		"total_pop": "323,072",
		"total_prison_population": 375,
		"female_prison_pop": 14,
		"male_prison_pop": 361,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 173,
		"latin_prison_pop": 109,
		"native_prison_pop": 4,
		"other_prison_pop": 14,
		"white_prison_pop": 75
	},
	{
		"county": "Saratoga County",
		"total_pop": "224,872",
		"total_prison_population": 303,
		"female_prison_pop": 38,
		"male_prison_pop": 265,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 44,
		"latin_prison_pop": 23,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 8,
		"white_prison_pop": 228
	},
	{
		"county": "Schenectady County",
		"total_pop": "155,340",
		"total_prison_population": 765,
		"female_prison_pop": 55,
		"male_prison_pop": 710,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 430,
		"latin_prison_pop": 103,
		"native_prison_pop": 8,
		"other_prison_pop": 19,
		"white_prison_pop": 205
	},
	{
		"county": "Schoharie County",
		"total_pop": "31,795",
		"total_prison_population": 41,
		"female_prison_pop": 4,
		"male_prison_pop": 37,
		"asian_prison_pop": 0,
		"black_prison_pop": "Not Available",
		"latin_prison_pop": "Not Available",
		"native_prison_pop": 0,
		"other_prison_pop": 3,
		"white_prison_pop": 38
	},
	{
		"county": "Schuyler County",
		"total_pop": "18,170",
		"total_prison_population": 44,
		"female_prison_pop": 6,
		"male_prison_pop": 38,
		"asian_prison_pop": 0,
		"black_prison_pop": "Not Available",
		"latin_prison_pop": "Not Available",
		"native_prison_pop": "Not Available",
		"other_prison_pop": 5,
		"white_prison_pop": 39
	},
	{
		"county": "Seneca County",
		"total_pop": "34,890",
		"total_prison_population": 73,
		"female_prison_pop": 8,
		"male_prison_pop": 65,
		"asian_prison_pop": 0,
		"black_prison_pop": 13,
		"latin_prison_pop": 6,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 1,
		"white_prison_pop": 53
	},
	{
		"county": "St. Lawrence County",
		"total_pop": "111,601",
		"total_prison_population": 306,
		"female_prison_pop": 18,
		"male_prison_pop": 288,
		"asian_prison_pop": 0,
		"black_prison_pop": 25,
		"latin_prison_pop": 8,
		"native_prison_pop": 4,
		"other_prison_pop": 11,
		"white_prison_pop": 258
	},
	{
		"county": "Steuben County",
		"total_pop": "98,208",
		"total_prison_population": 285,
		"female_prison_pop": 25,
		"male_prison_pop": 260,
		"asian_prison_pop": 0,
		"black_prison_pop": 47,
		"latin_prison_pop": 8,
		"native_prison_pop": 7,
		"other_prison_pop": 0,
		"white_prison_pop": 223
	},
	{
		"county": "Suffolk County",
		"total_pop": "1,500,638",
		"total_prison_population": "2,117",
		"female_prison_pop": 83,
		"male_prison_pop": "2,034",
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 869,
		"latin_prison_pop": 472,
		"native_prison_pop": 27,
		"other_prison_pop": 44,
		"white_prison_pop": 705
	},
	{
		"county": "Sullivan County",
		"total_pop": "75,852",
		"total_prison_population": 388,
		"female_prison_pop": 24,
		"male_prison_pop": 364,
		"asian_prison_pop": 0,
		"black_prison_pop": 125,
		"latin_prison_pop": 74,
		"native_prison_pop": 7,
		"other_prison_pop": 9,
		"white_prison_pop": 173
	},
	{
		"county": "Tioga County",
		"total_pop": "49,820",
		"total_prison_population": 78,
		"female_prison_pop": 6,
		"male_prison_pop": 72,
		"asian_prison_pop": 0,
		"black_prison_pop": 6,
		"latin_prison_pop": 6,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 1,
		"white_prison_pop": 65
	},
	{
		"county": "Tompkins County",
		"total_pop": "104,286",
		"total_prison_population": 171,
		"female_prison_pop": 12,
		"male_prison_pop": 159,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 59,
		"latin_prison_pop": 10,
		"native_prison_pop": 4,
		"other_prison_pop": 6,
		"white_prison_pop": 92
	},
	{
		"county": "Ulster County",
		"total_pop": "180,763",
		"total_prison_population": 642,
		"female_prison_pop": 28,
		"male_prison_pop": 614,
		"asian_prison_pop": 0,
		"black_prison_pop": 270,
		"latin_prison_pop": 83,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 21,
		"white_prison_pop": 268
	},
	{
		"county": "Warren County",
		"total_pop": "64,901",
		"total_prison_population": 355,
		"female_prison_pop": 57,
		"male_prison_pop": 298,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 62,
		"latin_prison_pop": 21,
		"native_prison_pop": 5,
		"other_prison_pop": 8,
		"white_prison_pop": 259
	},
	{
		"county": "Washington County",
		"total_pop": "62,478",
		"total_prison_population": 236,
		"female_prison_pop": 20,
		"male_prison_pop": 216,
		"asian_prison_pop": 0,
		"black_prison_pop": 30,
		"latin_prison_pop": 17,
		"native_prison_pop": 4,
		"other_prison_pop": 10,
		"white_prison_pop": 175
	},
	{
		"county": "Wayne County",
		"total_pop": "91,856",
		"total_prison_population": 210,
		"female_prison_pop": 15,
		"male_prison_pop": 195,
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 76,
		"latin_prison_pop": 19,
		"native_prison_pop": 4,
		"other_prison_pop": 3,
		"white_prison_pop": 108
	},
	{
		"county": "Westchester County",
		"total_pop": "972,742",
		"total_prison_population": "1,301",
		"female_prison_pop": 37,
		"male_prison_pop": "1,264",
		"asian_prison_pop": "Not Available",
		"black_prison_pop": 719,
		"latin_prison_pop": 372,
		"native_prison_pop": 6,
		"other_prison_pop": 31,
		"white_prison_pop": 173
	},
	{
		"county": "Wyoming County",
		"total_pop": "41,160",
		"total_prison_population": 138,
		"female_prison_pop": 14,
		"male_prison_pop": 124,
		"asian_prison_pop": 0,
		"black_prison_pop": 17,
		"latin_prison_pop": 9,
		"native_prison_pop": "Not Available",
		"other_prison_pop": 3,
		"white_prison_pop": 109
	},
	{
		"county": "Yates County",
		"total_pop": "25,150",
		"total_prison_population": 50,
		"female_prison_pop": 6,
		"male_prison_pop": 44,
		"asian_prison_pop": 0,
		"black_prison_pop": "Not Available",
		"latin_prison_pop": 4,
		"native_prison_pop": 0,
		"other_prison_pop": 3,
		"white_prison_pop": 43
	}
]